/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import communication.Communication;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Klijent;
import model.Ugovor;

/**
 *
 * @author Marko
 */
public class GlavnaFormaKlijent extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaFormaKlijent
     */
    private Communication communication = Communication.getInstance();
    private Klijent klijent;

    public GlavnaFormaKlijent(Klijent klijent) {
        this.klijent = klijent;
        initComponents();
        setTitle("Klijent: " + klijent.toString());
        setLocationRelativeTo(null);
        popuniInicijalno();
    }

    private void popuniInicijalno() {
        txtEmail.setEnabled(false);
        txtImePrezime.setEnabled(false);
        txtTelefon.setEnabled(false);
        txtKategorija.setEnabled(false);
        txtLozinka.setEnabled(false);
        btnIzmeniPodatke.setVisible(true);
        btnOdustani.setVisible(false);
        btnPotvrdiIzmenu.setVisible(false);

        txtEmail.setText(klijent.getEmail());
        txtImePrezime.setText(klijent.toString());
        txtTelefon.setText(klijent.getTelefon());
        txtKategorija.setText(klijent.getKategorija().toString());
        txtLozinka.setText(klijent.getLozinka());
        popuniCbUgovori();
    }

    private void popuniCbUgovori() {
        cbUgovori.removeAllItems();

        List<Ugovor> ugovori = communication.vratiSveUgovore();
        List<Ugovor> filterUgovori = new ArrayList<>();

        for (Ugovor u : ugovori) {
            if (u.getKlijent().equals(klijent)) {
                filterUgovori.add(u);
            }
        }

        for (Ugovor u : filterUgovori) {
            cbUgovori.addItem(u);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtImePrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtKategorija = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtLozinka = new javax.swing.JPasswordField();
        btnIzmeniPodatke = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();
        btnPotvrdiIzmenu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cbUgovori = new javax.swing.JComboBox<>();
        btnPrikaziDetaljno = new javax.swing.JButton();
        btnOdjava = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Moji podaci");

        jLabel2.setText("Ime i prezime:");

        jLabel3.setText("Email:");

        jLabel4.setText("Telefon:");

        jLabel5.setText("Kategorija:");

        jLabel6.setText("Lozinka:");

        btnIzmeniPodatke.setText("Izmeni podatke");
        btnIzmeniPodatke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniPodatkeActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        btnPotvrdiIzmenu.setText("Potvrdi izmenu");
        btnPotvrdiIzmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotvrdiIzmenuActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Moji ugovori");

        btnPrikaziDetaljno.setText("Prikazi detaljno");
        btnPrikaziDetaljno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziDetaljnoActionPerformed(evt);
            }
        });

        btnOdjava.setText("Odjava");
        btnOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjavaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrikaziDetaljno)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtImePrezime)
                            .addComponent(txtEmail)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtKategorija)
                            .addComponent(txtLozinka)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIzmeniPodatke)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPotvrdiIzmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(cbUgovori, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator3))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(btnOdjava, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeniPodatke)
                    .addComponent(btnOdustani)
                    .addComponent(btnPotvrdiIzmenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbUgovori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrikaziDetaljno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOdjava)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniPodatkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniPodatkeActionPerformed
        txtEmail.setEnabled(true);
        txtLozinka.setEnabled(true);
        txtTelefon.setEnabled(true);
        btnIzmeniPodatke.setVisible(false);
        btnPotvrdiIzmenu.setVisible(true);
        btnOdustani.setVisible(true);
    }//GEN-LAST:event_btnIzmeniPodatkeActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        popuniInicijalno();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnPotvrdiIzmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotvrdiIzmenuActionPerformed
        String noviEmail = txtEmail.getText();
        String novaLozinka = String.valueOf(txtLozinka.getPassword());
        String noviTelefon = txtTelefon.getText();

        Klijent izmenjeniKlijent = new Klijent();
        izmenjeniKlijent.setIdKlijent(klijent.getIdKlijent());
        izmenjeniKlijent.setEmail(noviEmail);
        izmenjeniKlijent.setTelefon(noviTelefon);
        izmenjeniKlijent.setLozinka(novaLozinka);

        int result = communication.izmeniKlijenta(klijent);
        if (result != 0) {
            JOptionPane.showMessageDialog(this, "Uspesna izmena podataka", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
            klijent.setEmail(noviEmail);
            klijent.setLozinka(novaLozinka);
            klijent.setTelefon(noviTelefon);
            popuniInicijalno();
        } else {
            JOptionPane.showMessageDialog(this, "Greska prilikom izmene podataka", "Greska", JOptionPane.ERROR_MESSAGE);
            popuniInicijalno();
        }
    }//GEN-LAST:event_btnPotvrdiIzmenuActionPerformed

    private void btnOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjavaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOdjavaActionPerformed

    private void btnPrikaziDetaljnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziDetaljnoActionPerformed
        Ugovor ugovor = (Ugovor) cbUgovori.getSelectedItem();
        if (ugovor == null) {
            JOptionPane.showMessageDialog(this, "Morate izabrati ugovor", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        FormaKlijentUgovor formaUgovor = new FormaKlijentUgovor(ugovor);
        formaUgovor.setVisible(true);
    }//GEN-LAST:event_btnPrikaziDetaljnoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniPodatke;
    private javax.swing.JButton btnOdjava;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnPotvrdiIzmenu;
    private javax.swing.JButton btnPrikaziDetaljno;
    private javax.swing.JComboBox<model.Ugovor> cbUgovori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtImePrezime;
    private javax.swing.JTextField txtKategorija;
    private javax.swing.JPasswordField txtLozinka;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
