/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms.paket_usluga;

import communication.Communication;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.PaketUsluga;
import model.TipPaketaUsluga;

/**
 *
 * @author Marko
 */
public class DodajIzmeniPaketUslugaForma extends javax.swing.JFrame {

    /**
     * Creates new form DodajIzmeniPaketUslugaForma
     */
    private Communication communication = Communication.getInstance();
    private PaketUslugaForma glavnaFormaPaketUsluga;

    public DodajIzmeniPaketUslugaForma(PaketUslugaForma glavnaFormaPaketUsluga) {
        this.glavnaFormaPaketUsluga = glavnaFormaPaketUsluga;
        initComponents();
        setTitle("Forma za dodavanje i izmenu paketa usluga");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbTipoviPaketa = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtNazivPaketa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCenaMesec = new javax.swing.JTextField();
        btnDodajPaket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tip:");

        cbTipoviPaketa.setModel(new DefaultComboBoxModel<>(TipPaketaUsluga.values()));

        jLabel2.setText("Naziv:");

        jLabel3.setText("Mesecna cena:");

        btnDodajPaket.setText("Dodaj paket");
        btnDodajPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajPaketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodajPaket)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNazivPaketa)
                        .addComponent(cbTipoviPaketa, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCenaMesec, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbTipoviPaketa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNazivPaketa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCenaMesec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnDodajPaket)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajPaketActionPerformed
        TipPaketaUsluga tip = (TipPaketaUsluga) cbTipoviPaketa.getSelectedItem();
        String naziv = txtNazivPaketa.getText();
        if (naziv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Paket mora imati naziv", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double cenaMesec = 0;
        try {
            cenaMesec = Double.parseDouble(txtCenaMesec.getText());
            if (cenaMesec < 0) {
                JOptionPane.showMessageDialog(this, "Cena mora biti pozitivan broj", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cena mora biti broj", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        PaketUsluga paket = new PaketUsluga(tip, naziv, cenaMesec);
        int result = communication.dodajPaketUsluga(paket);
        if (result == 0) {
            JOptionPane.showMessageDialog(this, "Greska prilikom dodavanja paketa", "Greska", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Uspesno dodavanje paketa", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
            glavnaFormaPaketUsluga.popuniTabeluPaketiUsluga();
            this.dispose();
        }
    }//GEN-LAST:event_btnDodajPaketActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajPaket;
    private javax.swing.JComboBox<model.TipPaketaUsluga> cbTipoviPaketa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCenaMesec;
    private javax.swing.JTextField txtNazivPaketa;
    // End of variables declaration//GEN-END:variables
}
