/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms.kategorija_klijenta;

import communication.Communication;
import javax.swing.JOptionPane;
import model.KategorijaKlijenta;

/**
 *
 * @author Marko
 */
public class DodajIzmeniKategorijaKlijentaForma extends javax.swing.JFrame {

    /**
     * Creates new form DodajIzmeniKategorijaKlijentaForma
     */
    private Communication communication = Communication.getInstance();
    private KategorijaKlijentaForma glavnaForma;
    private KategorijaKlijenta kategorija;

    public DodajIzmeniKategorijaKlijentaForma(KategorijaKlijentaForma glavnaForma, KategorijaKlijenta kategorija) {
        this.glavnaForma = glavnaForma;
        this.kategorija = kategorija;
        initComponents();
        setTitle("Forma za dodavanje i izmenu kategorija klijenta");
        setLocationRelativeTo(null);
        showHideButtons();
    }

    private void showHideButtons() {
        if (kategorija == null) {
            btnIzmeniKategoriju.setVisible(false);
            btnDodajKategoriju.setVisible(true);
        } else {
            btnIzmeniKategoriju.setVisible(true);
            btnDodajKategoriju.setVisible(false);
            txtNaziv.setText(kategorija.getNaziv());
            txtPopust.setText(String.valueOf(kategorija.getProcenatPopusta()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPopust = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnDodajKategoriju = new javax.swing.JButton();
        btnIzmeniKategoriju = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Naziv:");

        jLabel2.setText("Popust:");

        jLabel3.setText("%");

        btnDodajKategoriju.setText("Dodaj kategoriju");
        btnDodajKategoriju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajKategorijuActionPerformed(evt);
            }
        });

        btnIzmeniKategoriju.setText("Izmeni kategoriju");
        btnIzmeniKategoriju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniKategorijuActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnOdustani, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzmeniKategoriju, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDodajKategoriju, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addComponent(btnDodajKategoriju)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeniKategoriju)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(btnOdustani)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnDodajKategorijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajKategorijuActionPerformed
        String naziv = txtNaziv.getText();
        if (naziv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kategorija mora imati naziv", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int popust = 0;
        try {
            popust = Integer.parseInt(txtPopust.getText());
            if (popust < 0) {
                JOptionPane.showMessageDialog(this, "Popust mora biti pozitivan broj", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Popust mora biti broj", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        KategorijaKlijenta kategorija = new KategorijaKlijenta(naziv, popust);

        int result = communication.dodajKategorijuKlijenta(kategorija);

        if (result == 0) {
            JOptionPane.showMessageDialog(this, "Greska prilikom dodavanja kategorije", "Greska", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Uspesno dodavanje kategorije", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
            glavnaForma.popuniTabeluKategorijaKlijenta();
            this.dispose();
        }
    }//GEN-LAST:event_btnDodajKategorijuActionPerformed

    private void btnIzmeniKategorijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniKategorijuActionPerformed
        String noviNaziv = txtNaziv.getText();
        if (noviNaziv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kategorija mora imati naziv", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int noviPopust = 0;
        try {
            noviPopust = Integer.parseInt(txtPopust.getText());
            if (noviPopust <= 0) {
                JOptionPane.showMessageDialog(this, "Popust mora biti pozitivan broj", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Popust mora biti broj", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        KategorijaKlijenta novaKategorija = new KategorijaKlijenta(
                kategorija.getIdKategorijaKlijenta(),
                noviNaziv,
                noviPopust
        );

        int result = communication.izmeniKategorijuKlijenta(novaKategorija);
        if (result == 0) {
            JOptionPane.showMessageDialog(this, "Greska prilikom izmene kategorije", "Greska", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Uspesna izmena kategorije", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
            glavnaForma.popuniTabeluKategorijaKlijenta();
            this.dispose();
        }
    }//GEN-LAST:event_btnIzmeniKategorijuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajKategoriju;
    private javax.swing.JButton btnIzmeniKategoriju;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtPopust;
    // End of variables declaration//GEN-END:variables
}
