/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms.kategorija_klijenta;

import communication.Communication;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.KategorijaKlijenta;

/**
 *
 * @author Marko
 */
public class KategorijaKlijentaForma extends javax.swing.JFrame {

    /**
     * Creates new form KategorijaKlijentaForma
     */
    private Communication communication = Communication.getInstance();
    private DodajIzmeniKategorijaKlijentaForma formaKategorijaDodajIzmeni;
    private List<KategorijaKlijenta> kategorije;

    public List<KategorijaKlijenta> getKategorije() {
        return kategorije;
    }

    public KategorijaKlijentaForma() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Forma za rad sa kategorijama klijenta");
        setLocationRelativeTo(null);
        popuniTabeluKategorijaKlijenta();
    }

    public void popuniTabeluKategorijaKlijenta() {
        kategorije = communication.vratiSveKategorijeKlijenta();
        if (kategorije != null) {
            TableModelKategorijaKlijenta tmkk = new TableModelKategorijaKlijenta(kategorije);
            tblKategorijeKlijenta.setModel(tmkk);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKategorijeKlijenta = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnKrajRada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblKategorijeKlijenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKategorijeKlijenta);

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnKrajRada.setText("Kraj rada");
        btnKrajRada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKrajRadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKrajRada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnIzmeni)
                    .addComponent(btnObrisi)
                    .addComponent(btnKrajRada))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKrajRadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKrajRadaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnKrajRadaActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        formaKategorijaDodajIzmeni = new DodajIzmeniKategorijaKlijentaForma(this, null);
        formaKategorijaDodajIzmeni.setVisible(true);
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        TableModelKategorijaKlijenta tmkk = (TableModelKategorijaKlijenta) tblKategorijeKlijenta.getModel();
        int red = tblKategorijeKlijenta.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Morate selektovani jedan red", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        KategorijaKlijenta kategorija = tmkk.getKategorijeKlijenta().get(red);
        formaKategorijaDodajIzmeni = new DodajIzmeniKategorijaKlijentaForma(this, kategorija);
        formaKategorijaDodajIzmeni.setVisible(true);
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        TableModelKategorijaKlijenta tmkk = (TableModelKategorijaKlijenta) tblKategorijeKlijenta.getModel();
        int red = tblKategorijeKlijenta.getSelectedRow();

        if (red == -1) {
            JOptionPane.showMessageDialog(this,
                    "Morate selektovati jedan red.",
                    "Greška",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        KategorijaKlijenta kategorija = tmkk.getKategorijeKlijenta().get(red);
        int choice = JOptionPane.showConfirmDialog(this,
                "Da li ste sigurni da želite da obrišete ovu kategoriju?",
                "Brisanje",
                JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            int result = communication.obrisiKategorijuKlijenta(kategorija);

            if (result == 0) {
                JOptionPane.showMessageDialog(this,
                        "Došlo je do greške prilikom brisanja kategorije klijenta.",
                        "Greška",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Brisanje kategorije klijenta Uspešno izvršeno.",
                        "Uspešno",
                        JOptionPane.INFORMATION_MESSAGE);
            }

            popuniTabeluKategorijaKlijenta();
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnKrajRada;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKategorijeKlijenta;
    // End of variables declaration//GEN-END:variables
}
