/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import communication.Communication;
import forms.kategorija_klijenta.KategorijaKlijentaForma;
import forms.klijent.KlijentForma;
import forms.paket_usluga.PaketUslugaForma;
import forms.radno_vreme.RadnoVremeForma;
import forms.ugovor.UgovorGlavnaForma;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.RadnoVreme;
import model.Zaposleni;
import thread.TimeThread;

/**
 *
 * @author Marko
 */
public class ZaposleniGlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form ZaposleniGlavnaForma
     */
    private Zaposleni zaposleni;
    private PaketUslugaForma formaPaketUsluga;
    private KategorijaKlijentaForma formaKategorijaKlijenta;
    private KlijentForma formaKlijent;
    private RadnoVremeForma formaRadnoVreme;
    private UgovorGlavnaForma formaUgovor;
    private Communication communication = Communication.getInstance();

    public ZaposleniGlavnaForma(Zaposleni zaposleni) {
        initComponents();
        this.zaposleni = zaposleni;
        setTitle("Zaposleni: " + zaposleni.toString());
        setLocationRelativeTo(null);
        startClock();

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                try {
                    communication.logout(zaposleni);
                    System.out.println("Zaposleni " + zaposleni.toString() + " je odjavljen sa servera.");
                } catch (Exception ex) {
                    System.out.println("Greška pri odjavljivanju: " + ex.getMessage());
                }
            }
        });
    }

    private void startClock() {
        txtSmena.setEnabled(false);
        TimeThread thread = new TimeThread(lblVreme, lblDatum, txtSmena);
        thread.setDaemon(true);
        thread.start();
    }

    private boolean validateSmena() {
        List<RadnoVreme> radnaVremena = communication.vratiSveRadnoVreme();
        List<RadnoVreme> zaposleniRadnoVreme = new ArrayList<>();

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        LocalDate datumIzLabel = null;

        try {
            datumIzLabel = LocalDate.parse(lblDatum.getText(), formatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Neispravan format datuma u labeli!", "Greška", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        for (RadnoVreme rv : radnaVremena) {
            if (rv.getZaposleni().equals(zaposleni) && rv.getDatum().equals(datumIzLabel)) {
                zaposleniRadnoVreme.add(rv);
            }
        }

        for (RadnoVreme zrv : zaposleniRadnoVreme) {
            if (zrv.getSmena().getNaziv().equals(txtSmena.getText())) {
                return true;
            }
        }

        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPaketUsluga = new javax.swing.JButton();
        btnKategorijeKlijenata = new javax.swing.JButton();
        btnKlijent = new javax.swing.JButton();
        btnUgovori = new javax.swing.JButton();
        btnRadnoVreme = new javax.swing.JButton();
        btnKrajRada = new javax.swing.JButton();
        lblVreme = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSmena = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblDatum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPaketUsluga.setText("Paketi usluga");
        btnPaketUsluga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaketUslugaActionPerformed(evt);
            }
        });

        btnKategorijeKlijenata.setText("Kategorije klijenata");
        btnKategorijeKlijenata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKategorijeKlijenataActionPerformed(evt);
            }
        });

        btnKlijent.setText("Klijent");
        btnKlijent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlijentActionPerformed(evt);
            }
        });

        btnUgovori.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUgovori.setText("Ugovori");
        btnUgovori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUgovoriActionPerformed(evt);
            }
        });

        btnRadnoVreme.setText("Radno vreme");
        btnRadnoVreme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadnoVremeActionPerformed(evt);
            }
        });

        btnKrajRada.setText("Kraj rada");
        btnKrajRada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKrajRadaActionPerformed(evt);
            }
        });

        lblVreme.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVreme.setText("00:00:00");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Smena:");

        lblDatum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDatum.setText("DD-MM-YYYY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnPaketUsluga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnKategorijeKlijenata, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                        .addComponent(btnKlijent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnUgovori, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnRadnoVreme, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                        .addComponent(btnKrajRada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 69, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSmena, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtSmena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDatum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblVreme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPaketUsluga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKategorijeKlijenata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKlijent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUgovori, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRadnoVreme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKrajRada)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPaketUslugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaketUslugaActionPerformed
        if (validateSmena()) {
            formaPaketUsluga = new PaketUslugaForma();
            formaPaketUsluga.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Trenutno nije Vase radno vreme", "Greška", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnPaketUslugaActionPerformed

    private void btnKategorijeKlijenataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKategorijeKlijenataActionPerformed
        if (validateSmena()) {
            formaKategorijaKlijenta = new KategorijaKlijentaForma();
            formaKategorijaKlijenta.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Trenutno nije Vase radno vreme", "Greška", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnKategorijeKlijenataActionPerformed

    private void btnKlijentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlijentActionPerformed
        if (validateSmena()) {
            formaKlijent = new KlijentForma();
            formaKlijent.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Trenutno nije Vase radno vreme", "Greška", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnKlijentActionPerformed

    private void btnUgovoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUgovoriActionPerformed
        if (validateSmena()) {
            formaUgovor = new UgovorGlavnaForma(zaposleni);
            formaUgovor.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Trenutno nije Vase radno vreme", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUgovoriActionPerformed

    private void btnKrajRadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKrajRadaActionPerformed
        boolean result = communication.logout(zaposleni);
        if (result) {
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Došlo je do greške prilikom odjave", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnKrajRadaActionPerformed

    private void btnRadnoVremeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadnoVremeActionPerformed
        formaRadnoVreme = new RadnoVremeForma(zaposleni);
        formaRadnoVreme.setVisible(true);
    }//GEN-LAST:event_btnRadnoVremeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKategorijeKlijenata;
    private javax.swing.JButton btnKlijent;
    private javax.swing.JButton btnKrajRada;
    private javax.swing.JButton btnPaketUsluga;
    private javax.swing.JButton btnRadnoVreme;
    private javax.swing.JButton btnUgovori;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblVreme;
    private javax.swing.JTextField txtSmena;
    // End of variables declaration//GEN-END:variables
}
