/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import forms.paket_usluga.PaketUslugaForma;
import model.Zaposleni;

/**
 *
 * @author Marko
 */
public class ZaposleniGlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form ZaposleniGlavnaForma
     */
    private Zaposleni zaposleni;
    private PaketUslugaForma formaPaketUsluga;
    public ZaposleniGlavnaForma(Zaposleni zaposleni) {
        initComponents();
        this.zaposleni = zaposleni;
        setTitle("Zaposleni: " + zaposleni.toString());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPaketUsluga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPaketUsluga.setText("Paketi usluga");
        btnPaketUsluga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaketUslugaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnPaketUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnPaketUsluga)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPaketUslugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaketUslugaActionPerformed
        formaPaketUsluga = new PaketUslugaForma();
        formaPaketUsluga.setVisible(true);
    }//GEN-LAST:event_btnPaketUslugaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaketUsluga;
    // End of variables declaration//GEN-END:variables
}
