/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import forms.kategorija_klijenta.KategorijaKlijentaForma;
import forms.klijent.KlijentForma;
import forms.paket_usluga.PaketUslugaForma;
import forms.radno_vreme.RadnoVremeForma;
import forms.ugovor.UgovorGlavnaForma;
import model.Zaposleni;

/**
 *
 * @author Marko
 */
public class ZaposleniGlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form ZaposleniGlavnaForma
     */
    private Zaposleni zaposleni;
    private PaketUslugaForma formaPaketUsluga;
    private KategorijaKlijentaForma formaKategorijaKlijenta;
    private KlijentForma formaKlijent;
    private RadnoVremeForma formaRadnoVreme;
    private UgovorGlavnaForma formaUgovor;

    public ZaposleniGlavnaForma(Zaposleni zaposleni) {
        initComponents();
        this.zaposleni = zaposleni;
        setTitle("Zaposleni: " + zaposleni.toString());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPaketUsluga = new javax.swing.JButton();
        btnKategorijeKlijenata = new javax.swing.JButton();
        btnKlijent = new javax.swing.JButton();
        btnUgovori = new javax.swing.JButton();
        btnRadnoVreme = new javax.swing.JButton();
        btnKrajRada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPaketUsluga.setText("Paketi usluga");
        btnPaketUsluga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaketUslugaActionPerformed(evt);
            }
        });

        btnKategorijeKlijenata.setText("Kategorije klijenata");
        btnKategorijeKlijenata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKategorijeKlijenataActionPerformed(evt);
            }
        });

        btnKlijent.setText("Klijent");
        btnKlijent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlijentActionPerformed(evt);
            }
        });

        btnUgovori.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUgovori.setText("Ugovori");
        btnUgovori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUgovoriActionPerformed(evt);
            }
        });

        btnRadnoVreme.setText("Radno vreme");
        btnRadnoVreme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadnoVremeActionPerformed(evt);
            }
        });

        btnKrajRada.setText("Kraj rada");
        btnKrajRada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKrajRadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPaketUsluga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKategorijeKlijenata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKlijent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUgovori, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(81, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRadnoVreme, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(btnKrajRada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnPaketUsluga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKategorijeKlijenata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKlijent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUgovori, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnRadnoVreme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKrajRada)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPaketUslugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaketUslugaActionPerformed
        formaPaketUsluga = new PaketUslugaForma();
        formaPaketUsluga.setVisible(true);
    }//GEN-LAST:event_btnPaketUslugaActionPerformed

    private void btnKategorijeKlijenataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKategorijeKlijenataActionPerformed
        formaKategorijaKlijenta = new KategorijaKlijentaForma();
        formaKategorijaKlijenta.setVisible(true);
    }//GEN-LAST:event_btnKategorijeKlijenataActionPerformed

    private void btnKlijentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlijentActionPerformed
        formaKlijent = new KlijentForma();
        formaKlijent.setVisible(true);
    }//GEN-LAST:event_btnKlijentActionPerformed

    private void btnUgovoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUgovoriActionPerformed
        formaUgovor = new UgovorGlavnaForma(zaposleni);
        formaUgovor.setVisible(true);
    }//GEN-LAST:event_btnUgovoriActionPerformed

    private void btnKrajRadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKrajRadaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnKrajRadaActionPerformed

    private void btnRadnoVremeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadnoVremeActionPerformed
        formaRadnoVreme = new RadnoVremeForma(zaposleni);
        formaRadnoVreme.setVisible(true);
    }//GEN-LAST:event_btnRadnoVremeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKategorijeKlijenata;
    private javax.swing.JButton btnKlijent;
    private javax.swing.JButton btnKrajRada;
    private javax.swing.JButton btnPaketUsluga;
    private javax.swing.JButton btnRadnoVreme;
    private javax.swing.JButton btnUgovori;
    // End of variables declaration//GEN-END:variables
}
