/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms.ugovor;

import communication.Communication;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Klijent;
import model.PaketUsluga;
import model.StatusUgovora;
import model.StavkaUgovora;
import model.TipPaketaUsluga;
import model.Ugovor;
import model.Zaposleni;
import model.helper.UgovorSaStavkama;

/**
 *
 * @author Marko
 */
public class KreirajUgovorForma extends javax.swing.JFrame {

    /**
     * Creates new form KreirajUgovorForma
     */
    private Ugovor ugovor;
    private Zaposleni zaposleni;
    private Klijent klijent;
    private Communication communication = Communication.getInstance();
    private List<StavkaUgovora> stavkeUgovora = new ArrayList<>();

    public KreirajUgovorForma(Zaposleni zaposleni, Klijent klijent, Ugovor ugovor) {
        this.zaposleni = zaposleni;
        this.klijent = klijent;
        this.ugovor = ugovor;
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Forma za kreiranje ugovora");
        setLocationRelativeTo(null);
        popuniInicijalnimPodacima();
    }

    private void izracunajCenuUgovora() {
        double suma = 0;
        for (StavkaUgovora stavka : stavkeUgovora) {
            suma += stavka.getFinalnaCena();
        }
        txtCena.setText(String.valueOf(suma));
    }

    private void popuniTabeluStavkeUgovora() {
        TableModelStavkaUgovora tmsu = new TableModelStavkaUgovora(stavkeUgovora);
        tblStavkeUgovora.setModel(tmsu);
    }

    private void popuniInicijalnimPodacima() {
        popuniTabeluStavkeUgovora();
        cbTipPaketaUsluga.setSelectedIndex(-1);
        cbPaketiUsluga.setEnabled(false);
        cbPaketiUsluga.setSelectedIndex(-1);
        txtKlijent.setText(klijent.toString());
        txtKlijent.setEnabled(false);
        txtZaposleni.setText(zaposleni.toString());
        txtZaposleni.setEnabled(false);

        //Datum pocetka
        LocalDate danasnjiDatum = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String formattedDatumPocetka = danasnjiDatum.format(formatter);
        txtDatumPocetka.setText(formattedDatumPocetka);
        txtDatumPocetka.setEnabled(false);

        //Datum isteka
        LocalDate datumIstekaDefault = danasnjiDatum.plusYears(2);
        String formattedDatumIsteka = datumIstekaDefault.format(formatter);
        txtDatumIsteka.setText(formattedDatumIsteka);
        txtDatumIsteka.setEnabled(false);

        //Procenat popusta
        int popust = klijent.getKategorija().getProcenatPopusta();
        txtPopust.setText(popust + "%");
        txtPopust.setEnabled(false);

        //Status ugovora
        cbStatusUgovora.setSelectedItem(StatusUgovora.AKTIVAN);
        cbStatusUgovora.setEnabled(false);

        //Ukupna cena
        txtCena.setEnabled(false);
        
        if (ugovor != null) {
            //popuniZaIzmeni();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtZaposleni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtKlijent = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDatumPocetka = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDatumIsteka = new javax.swing.JTextField();
        btnRucniUnos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtPopust = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkeUgovora = new javax.swing.JTable();
        lblTipPaketa = new javax.swing.JLabel();
        lblPaket = new javax.swing.JLabel();
        cbPaketiUsluga = new javax.swing.JComboBox<>();
        cbTipPaketaUsluga = new javax.swing.JComboBox<>();
        btnDodajStavku = new javax.swing.JButton();
        btnUkloniStavku = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        btnKreirajUgovor = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();
        cbStatusUgovora = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Zaposleni:");

        jLabel2.setText("Klijent:");

        jLabel3.setText("Datum pocetka ugovorne obaveze:");

        jLabel4.setText("Datum isteka ugovorne obaveze:");

        btnRucniUnos.setText("Ručni unos");
        btnRucniUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRucniUnosActionPerformed(evt);
            }
        });

        jLabel5.setText("Procenat popusta:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Stavke ugovora");

        tblStavkeUgovora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Paket usluga", "Tip paketa", "Cena sa popustom"
            }
        ));
        jScrollPane1.setViewportView(tblStavkeUgovora);

        lblTipPaketa.setText("Tip paketa usluga:");

        lblPaket.setText("Paket:");

        cbTipPaketaUsluga.setModel(new DefaultComboBoxModel<>(TipPaketaUsluga.values())
        );
        cbTipPaketaUsluga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipPaketaUslugaActionPerformed(evt);
            }
        });

        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnUkloniStavku.setText("Ukloni stavku");
        btnUkloniStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniStavkuActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Cena i status");

        jLabel10.setText("Status ugovora:");

        jLabel11.setText("Ukupna cena:");

        btnKreirajUgovor.setText("Kreiraj ugovor");
        btnKreirajUgovor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajUgovorActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        cbStatusUgovora.setModel(new DefaultComboBoxModel<>(StatusUgovora.values())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDatumPocetka)
                                    .addComponent(txtDatumIsteka, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRucniUnos, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtZaposleni, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(txtKlijent))
                                .addGap(59, 59, 59)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipPaketa, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbPaketiUsluga, 0, 384, Short.MAX_VALUE)
                                    .addComponent(cbTipPaketaUsluga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnUkloniStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(264, 264, 264)
                                .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbStatusUgovora, 0, 256, Short.MAX_VALUE)
                                    .addComponent(txtCena))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKreirajUgovor, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDatumIsteka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRucniUnos, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipPaketa)
                    .addComponent(cbTipPaketaUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaket)
                    .addComponent(cbPaketiUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajStavku)
                    .addComponent(btnUkloniStavku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cbStatusUgovora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnKreirajUgovor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnOdustani)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRucniUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRucniUnosActionPerformed
        txtDatumPocetka.setEnabled(true);
        txtDatumIsteka.setEnabled(true);
    }//GEN-LAST:event_btnRucniUnosActionPerformed

    private void cbTipPaketaUslugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipPaketaUslugaActionPerformed
        List<PaketUsluga> paketi = communication.vratiSvePakete();
        List<PaketUsluga> filterPaketi = new ArrayList<>();
        TipPaketaUsluga selektovaniTip = (TipPaketaUsluga) cbTipPaketaUsluga.getSelectedItem();
        for (PaketUsluga paket : paketi) {
            if (paket.getTip().equals(selektovaniTip)) {
                filterPaketi.add(paket);
            }
        }
        cbPaketiUsluga.removeAllItems();
        for (PaketUsluga paket : filterPaketi) {
            cbPaketiUsluga.addItem(paket);
        }
        cbPaketiUsluga.setEnabled(true);
    }//GEN-LAST:event_cbTipPaketaUslugaActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        int procenatPopusta = klijent.getKategorija().getProcenatPopusta();
        PaketUsluga odabraniPaket = (PaketUsluga) cbPaketiUsluga.getSelectedItem();
        if (odabraniPaket == null) {
            JOptionPane.showMessageDialog(this, "Morate prvo odabrati paket", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double osnovnaCenaPaketa = odabraniPaket.getCenaMesec();
        double cenaSaPopustom = osnovnaCenaPaketa - (osnovnaCenaPaketa * procenatPopusta / 100);
        StavkaUgovora novaStavkaUgovora = new StavkaUgovora();
        novaStavkaUgovora.setPaketUsluga(odabraniPaket);
        novaStavkaUgovora.setFinalnaCena(cenaSaPopustom);
        if (stavkeUgovora.contains(novaStavkaUgovora)) {
            JOptionPane.showMessageDialog(this, "Ovaj paket već postoji", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        stavkeUgovora.add(novaStavkaUgovora);
        popuniTabeluStavkeUgovora();
        izracunajCenuUgovora();
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnUkloniStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniStavkuActionPerformed
        TableModelStavkaUgovora tmsu = (TableModelStavkaUgovora) tblStavkeUgovora.getModel();
        int red = tblStavkeUgovora.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Morate selektovani jedan red", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        StavkaUgovora ukloniStavka = tmsu.getStavke().get(red);
        System.out.println(ukloniStavka);
        stavkeUgovora.remove(ukloniStavka);
        popuniTabeluStavkeUgovora();
        izracunajCenuUgovora();
    }//GEN-LAST:event_btnUkloniStavkuActionPerformed

    private void btnKreirajUgovorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajUgovorActionPerformed
        if (stavkeUgovora.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ugovor mora imati barem jednu stavku", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String datumPocetkaStr = txtDatumPocetka.getText();
        String datumIstekaStr = txtDatumIsteka.getText();
        LocalDate datumPocetka = null;
        LocalDate datumIsteka = null;
        try {
            datumPocetka = LocalDate.parse(datumPocetkaStr, formatter);
            datumIsteka = LocalDate.parse(datumIstekaStr, formatter);
            if (datumPocetka.isBefore(LocalDate.now())) {
                JOptionPane.showMessageDialog(this, "Datum početka ne moze biti u prošlosti", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (datumIsteka.isBefore(datumPocetka)) {
                JOptionPane.showMessageDialog(this, "Datum isteka ne može biti pre datuma početka", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this, "Neispravan format datuma", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int trajanjeMeseci = (int) ChronoUnit.MONTHS.between(datumPocetka, datumIsteka);

        double ukupnaCena = Double.parseDouble(txtCena.getText());

        StatusUgovora status = (StatusUgovora) cbStatusUgovora.getSelectedItem();

        Ugovor ugovor = new Ugovor(zaposleni, klijent, datumPocetka, datumIsteka, trajanjeMeseci, ukupnaCena, status);
        UgovorSaStavkama ugovorSaStavkama = new UgovorSaStavkama(ugovor, stavkeUgovora);
        int result = communication.dodajUgovorSaStavkama(ugovorSaStavkama);
        if (result != 0) {
            JOptionPane.showMessageDialog(this, "Ugovor uspešno kreiran", "Uspešno", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Greška prilikom kreiranja ugovora", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnKreirajUgovorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnKreirajUgovor;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnRucniUnos;
    private javax.swing.JButton btnUkloniStavku;
    private javax.swing.JComboBox<model.PaketUsluga> cbPaketiUsluga;
    private javax.swing.JComboBox<model.StatusUgovora> cbStatusUgovora;
    private javax.swing.JComboBox<model.TipPaketaUsluga> cbTipPaketaUsluga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblPaket;
    private javax.swing.JLabel lblTipPaketa;
    private javax.swing.JTable tblStavkeUgovora;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtDatumIsteka;
    private javax.swing.JTextField txtDatumPocetka;
    private javax.swing.JTextField txtKlijent;
    private javax.swing.JTextField txtPopust;
    private javax.swing.JTextField txtZaposleni;
    // End of variables declaration//GEN-END:variables

}
