/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms.ugovor;

import communication.Communication;
import forms.klijent.TableModelKlijent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Klijent;
import model.Zaposleni;

/**
 *
 * @author Marko
 */
public class UgovorGlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form UgovorGlavnaForma
     */
    private Zaposleni zaposleni;
    private Communication communication = Communication.getInstance();
    private KreirajUgovorForma formaKreirajUgovor;

    public UgovorGlavnaForma(Zaposleni zaposleni) {
        this.zaposleni = zaposleni;
        initComponents();
        setTitle("Forma za rad sa ugovorima");
        setLocationRelativeTo(null);
        popuniTabeluKlijenti();
    }

    private void popuniTabeluKlijenti() {
        List<Klijent> klijenti = communication.vratiSveKlijente();
        if (klijenti != null) {
            TableModelKlijent tmk = new TableModelKlijent(klijenti);
            tblKlijenti.setModel(tmk);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEmailKlijent = new javax.swing.JTextField();
        btnPretraziKlijente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKlijenti = new javax.swing.JTable();
        btnPrikaziSve = new javax.swing.JButton();
        btnKreirajNoviUgovor = new javax.swing.JButton();
        btnKrajRada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Email klijenta:");

        btnPretraziKlijente.setText("Pretrazi klijente");
        btnPretraziKlijente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziKlijenteActionPerformed(evt);
            }
        });

        tblKlijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKlijenti);

        btnPrikaziSve.setText("Prikazi sve");
        btnPrikaziSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziSveActionPerformed(evt);
            }
        });

        btnKreirajNoviUgovor.setText("Kreiraj novi ugovor");
        btnKreirajNoviUgovor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajNoviUgovorActionPerformed(evt);
            }
        });

        btnKrajRada.setText("Kraj rada");
        btnKrajRada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKrajRadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmailKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPretraziKlijente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrikaziSve, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(btnKreirajNoviUgovor)))
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(btnKrajRada, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrikaziSve, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtEmailKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPretraziKlijente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKreirajNoviUgovor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnKrajRada)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziKlijenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziKlijenteActionPerformed
        List<Klijent> klijenti = communication.vratiSveKlijente();
        if (klijenti != null) {
            List<Klijent> filterKlijenti = new ArrayList<>();
            String filterEmail = txtEmailKlijent.getText();
            for (Klijent k : klijenti) {
                if (k.getEmail().contains(filterEmail)) {
                    filterKlijenti.add(k);
                }
            }
            TableModelKlijent tmk = new TableModelKlijent(filterKlijenti);
            tblKlijenti.setModel(tmk);
        }
    }//GEN-LAST:event_btnPretraziKlijenteActionPerformed

    private void btnPrikaziSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziSveActionPerformed
        popuniTabeluKlijenti();
    }//GEN-LAST:event_btnPrikaziSveActionPerformed

    private void btnKreirajNoviUgovorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajNoviUgovorActionPerformed
        TableModelKlijent tmk = (TableModelKlijent) tblKlijenti.getModel();
        int red = tblKlijenti.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Morate prvo selektovani klijenta", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Klijent klijent = tmk.getKlijenti().get(red);
        formaKreirajUgovor = new KreirajUgovorForma(zaposleni, klijent);
        formaKreirajUgovor.setVisible(true);
    }//GEN-LAST:event_btnKreirajNoviUgovorActionPerformed

    private void btnKrajRadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKrajRadaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnKrajRadaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKrajRada;
    private javax.swing.JButton btnKreirajNoviUgovor;
    private javax.swing.JButton btnPretraziKlijente;
    private javax.swing.JButton btnPrikaziSve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKlijenti;
    private javax.swing.JTextField txtEmailKlijent;
    // End of variables declaration//GEN-END:variables
}
